version: '3.3'
services:
  # igamt-mongo-db:
  #       image: mongo:latest
  #       container_name: igamt-mongo-db
  #       environment:
  #         - MONGO_DATA_DIR: /data/data/
  #         - MONGO_LOG_DIR: /data/logs/
  #         #- MONGO_INITDB_ROOT_USERNAME: <admin-user>
  #         #- MONGO_INITDB_ROOT_PASSWORD: <admin-password>
  #         - MONGO_INITDB_DATABASE: igamt
  #       volumes:
  #         - ../data/hl7-igamt-mongo/db/logs:/data/logs/
  #         - ../data/hl7-igamt-mongo/db/data:/data/data/
  #       ports:
  #           - 27017:27017
  igamt-mongo-db:
    build: ./igamt-mongo-db
    image: igamt-mongo-db
    networks:
      - hl7
    container_name: igamt-mongo-db
    environment:
      MONGO_INITDB_DATABASE: igamt
    expose:
          - "27017"
    healthcheck:
        test: ["CMD-SHELL", "mongo localhost:27017 --eval 'db.serverStatus()' "]
        interval: 30s
        timeout: 30s
        retries: 3
    volumes:
        - ../../data/igamt-mongo-db/logs/:/var/log/mongodb/
        - ../../data/igamt-mongo-db/db:/data/db
        - ../../data/igamt-mongo-db/configdb:/data/configdb
    #env_file:
    #    - ./igamt-mongo-db/config/db.env
    #restart: always

  # igamt-mysql-db:
  #   image: mysql:5.7
  #   container_name: igamt-mysql-db
  #   networks:
  #     - hl7
  #   #restart: always
  #   environment:
  #     MYSQL_DATABASE: 'igl'
  #     MYSQL_USER: 'igluser'
  #     MYSQL_PASSWORD: ''
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   ports:
  #     - '3306:3306'
  #   expose:
  #     - '3306'
  #   volumes:
  #     - ../data/hl7-igamt/db/logs/:/var/log/mysql/
  #     - ../data/hl7-igamt/db/data/:/var/lib/mysql/

  igamt-mysql-db:
      build: ./common/hit-base-db-mdb
      image: igamt-mysql-db
      container_name: igamt-mysql-db
      networks:
        - hl7
      env_file:
          - ./igamt-mysql-db/db/config.env
      ports:
          - '3306:3306'
      expose:
          - '3306'
      healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
      volumes:
          - ../data/igamt-mysql-db/logs/:/var/log/mysql/
          - ../data/igamt-mysql-db/data/:/var/lib/mysql/
  # igamt:
  #   build: ./common/old-igamt
  #   image: igamt
  #   networks:
  #     - hl7
  #   container_name: igamt
  #   ports:
  #     - '8080:8080'
  #     - '8009:8009'
  #   expose:
  #       - "8009"
  #       - "8080"
  #   depends_on:
  #     - igamt-mysql-db
  #     - igamt-mongo-db

  igamt-tool:
    build: ./igamt-tool
    image: igamt-tool
    container_name: igamt-tool
    networks:
         - hl7
    ports:
      - '8080:8080'
      - '8009:8009'
    expose:
        - "8009"
        - "8080"
    #env_file:
    #    - ./hit-base-tool/db/config.env
    #    - ./hit-base-tool/app/config/config.env
    volumes:
        - ../data/igamt-tool/app/logs/config:/opt/data/config/
        - ../data/igamt-tool/app/logs/tomcat:/opt/tomcat/logs/
        - ../data/igamt-tool/app/logs/app:/opt/data/logs/
    depends_on:
        - igamt-mongo-db
        #  condition: service_healthy
        - igamt-mysql-db
        #  condition: service_healthy
    links:
        - igamt-mongo-db:igamt-mongo-db
        - igamt-mysql-db:igamt-mysql-db

  hl7-reverse-proxy:
      build: ./tools-reverse-proxy
      networks:
        - hl7
      image: hl7-reverse-proxy
      container_name: hl7-reverse-proxy
      volumes:
          - ../../data/hl7-reverse-proxy/logs/:/var/log/nginx/
          - ../../data/hl7-reverse-proxy/html:/usr/share/nginx/html:ro
      ports:
          - "80:80"
          - "443:443"
      depends_on:
          - igamt-tool
          - igamt-mongo-db
          - igamt-mysql-db
      links:
          - igamt-tool:igamt-tool
          - igamt-mongo-db:igamt-mongo-db
          - igamt-mysql-db:igamt-mysql-db

networks:
  hl7:
